[package]
name = "robot-api"
version = "0.1.0"
authors = ["Fredrik <fredrik.christenson@gmail.com>"]

[dependencies]
rocket = "0.3.14"
rocket_codegen = "0.3.14"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"